// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// lerp.cpp
cpp11::integers lerp_cpp(cpp11::integers x, cpp11::integers y, const float t);
extern "C" SEXP _mixboxr_lerp_cpp(SEXP x, SEXP y, SEXP t) {
  BEGIN_CPP11
    return cpp11::as_sexp(lerp_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(y), cpp11::as_cpp<cpp11::decay_t<const float>>(t)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mixboxr_lerp_cpp", (DL_FUNC) &_mixboxr_lerp_cpp, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mixboxr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
